import React from 'react'
import travelerLogo from '../../../assets/traveler_logo.png';
import completeImage from '../../../assets/complete.png';
import cancelImage from '../../../assets/cancel.png';
import axios from '../../api/axios';

export default function PageTitle({ pastOrders = [] }) {
  const handleExportHistory = async () => {
    if (pastOrders.length === 0) return;
    
    const jsPDF = (await import('jspdf')).default;
    const doc = new jsPDF();
    const currentYear = new Date().getFullYear();
    
    // Fetch all images first
    const allImageUuids = pastOrders.flatMap(order => 
      order.items?.flatMap(item => item.itemObj?.images || []) || []
    );
    
    const imageMapper = {};
    for (const uuid of allImageUuids) {
      try {
        const response = await axios.get(`storage/files/download/${uuid}`, {
          responseType: 'blob'
        });
        imageMapper[uuid] = URL.createObjectURL(response.data);
      } catch (error) {
        console.error(`Error fetching image ${uuid}:`, error);
      }
    }
    
    // Header for first page
    doc.setFillColor(33, 121, 100);
    doc.rect(0, 0, 210, 30, 'F');
    
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.setFont(undefined, 'bold');
    doc.text('✈', 20, 18);
    
    doc.setFontSize(10);
    doc.setFont(undefined, 'normal');
    doc.text('Professional Travel & Rental Services', 120, 12);
    doc.text('Order History Export', 120, 18);
    
    doc.setTextColor(0, 0, 0);
    
    // Add watermark to first page
    doc.addImage(completeImage, 'PNG', 60, 140, 90, 90);
    
    doc.setFontSize(18);
    doc.setFont(undefined, 'bold');
    doc.text('ORDER HISTORY REPORT', 20, 45);
    
    let yPos = 60;
    
    for (let orderIndex = 0; orderIndex < pastOrders.length; orderIndex++) {
      const order = pastOrders[orderIndex];
      
      // Check if we need a new page
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
        
        // Add watermark to new page
        doc.addImage(completeImage, 'PNG', 60, 140, 90, 90);
      }
      
      // Order header
      doc.setFillColor(33, 121, 100);
      doc.rect(20, yPos, 170, 15, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont(undefined, 'bold');
      doc.text(`ORDER ${orderIndex + 1}: ${order.orderCode}`, 25, yPos + 10);
      
      doc.setTextColor(0, 0, 0);
      yPos += 20;
      
      // Order details
      doc.setFillColor(248, 250, 252);
      doc.rect(20, yPos, 170, 25, 'F');
      doc.setDrawColor(23, 121, 100);
      doc.setLineWidth(0.5);
      doc.rect(20, yPos, 170, 25);
      
      doc.setFontSize(10);
      doc.setFont(undefined, 'normal');
      doc.text(`Customer: ${order.customerName}`, 25, yPos + 8);
      doc.text(`Status: ${order.status}`, 25, yPos + 15);
      doc.text(`Items: ${order.items?.length || 0}`, 120, yPos + 8);
      
      const totalAmount = order.items?.reduce((sum, item) => sum + parseFloat(item.totalPrice || 0), 0) || 0;
      doc.text(`Total: Rs. ${totalAmount.toFixed(2)}`, 120, yPos + 15);
      
      yPos += 35;
      
      // Item details
      for (let itemIndex = 0; itemIndex < (order.items?.length || 0); itemIndex++) {
        const item = order.items[itemIndex];
        
        if (yPos > 240) {
          doc.addPage();
          yPos = 20;
          doc.addImage(completeImage, 'PNG', 60, 140, 90, 90);
        }
        
        doc.setFillColor(250, 250, 250);
        doc.rect(30, yPos, 150, 35, 'F');
        doc.setDrawColor(200, 200, 200);
        doc.rect(30, yPos, 150, 35);
        
        // Add item image if available
        if (item.itemObj?.images?.[0] && imageMapper[item.itemObj.images[0]]) {
          try {
            doc.addImage(imageMapper[item.itemObj.images[0]], 'JPEG', 32, yPos + 2, 20, 15);
          } catch (error) {
            console.error('Error adding image to PDF:', error);
          }
        }
        
        doc.setFontSize(9);
        doc.text(`${itemIndex + 1}. ${item.itemObj?.name || 'Item ' + item.item}`, 55, yPos + 8);
        doc.text(`Qty: ${item.qty} | Days: ${item.rentalDays}`, 55, yPos + 15);
        doc.text(`Price: Rs. ${item.totalPrice}`, 120, yPos + 8);
        doc.text(`Status: ${item.status}`, 120, yPos + 15);
        
        yPos += 40;
      }
    }
    
    // Footer
    doc.setFillColor(248, 250, 252);
    doc.rect(0, 275, 210, 22, 'F');
    doc.setDrawColor(23, 121, 100);
    doc.line(0, 275, 210, 275);
    
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Order History Export - Generated by Traveler Management System', 20, 283);
    doc.text(`© ${currentYear} Traveler Inc. All rights reserved.`, 20, 288);
    
    doc.save(`Order-History-${new Date().toISOString().split('T')[0]}.pdf`);
  };
  return (
    <div className="flex flex-wrap justify-between gap-3 px-4 pb-8">
      <div className="flex flex-col gap-2">
        <h1 className="text-[#181811]  text-3xl md:text-4xl font-black leading-tight tracking-[-0.033em]">
          Your Bookings
        </h1>
        <p className="text-[#8c8b5f] text-base font-normal leading-normal">
          Track your current rentals and review past history.
        </p>
      </div>
      <div className="flex items-center">
        <button 
          onClick={handleExportHistory}
          disabled={pastOrders.length === 0}
          className="flex items-center gap-2 bg-white  border border-[#e6e6db]  px-4 py-2 rounded-full text-sm font-bold shadow-sm hover:bg-gray-50  transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <span className="material-symbols-outlined text-[18px]">download</span>
          Export History
        </button>
      </div>
    </div>
  )
}
